create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  age text not null,
  gender text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.body_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  height_cm double precision not null,
  weight_kg double precision not null,
  age text not null,
  gender text not null,
  photo_path text,
  photo_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists body_records_user_id_created_at_idx
  on public.body_records (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.body_records enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can view their own profile'
  ) then
    create policy "Users can view their own profile"
      on public.profiles
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can insert their own profile'
  ) then
    create policy "Users can insert their own profile"
      on public.profiles
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can update their own profile'
  ) then
    create policy "Users can update their own profile"
      on public.profiles
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'body_records' and policyname = 'Users can view their own body records'
  ) then
    create policy "Users can view their own body records"
      on public.body_records
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'body_records' and policyname = 'Users can insert their own body records'
  ) then
    create policy "Users can insert their own body records"
      on public.body_records
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'body_records' and policyname = 'Users can update their own body records'
  ) then
    create policy "Users can update their own body records"
      on public.body_records
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'body_records' and policyname = 'Users can delete their own body records'
  ) then
    create policy "Users can delete their own body records"
      on public.body_records
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;
end
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists body_records_set_updated_at on public.body_records;
create trigger body_records_set_updated_at
before update on public.body_records
for each row execute function public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('profile-photos', 'profile-photos', true)
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public can view profile photos'
  ) then
    create policy "Public can view profile photos"
      on storage.objects
      for select
      to public
      using (bucket_id = 'profile-photos');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'Users can upload their own profile photos'
  ) then
    create policy "Users can upload their own profile photos"
      on storage.objects
      for insert
      to authenticated
      with check (
        bucket_id = 'profile-photos'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'Users can update their own profile photos'
  ) then
    create policy "Users can update their own profile photos"
      on storage.objects
      for update
      to authenticated
      using (
        bucket_id = 'profile-photos'
        and (storage.foldername(name))[1] = auth.uid()::text
      )
      with check (
        bucket_id = 'profile-photos'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'Users can delete their own profile photos'
  ) then
    create policy "Users can delete their own profile photos"
      on storage.objects
      for delete
      to authenticated
      using (
        bucket_id = 'profile-photos'
        and (storage.foldername(name))[1] = auth.uid()::text
      );
  end if;
end
$$;
